### ISSUE TITLE
Windows wallet unable to send to linux/mac 

### ISSUE THREAD

**Issue by BitHighlander** [BitHighlander/diagonAlley#4]
Windows version is based off version 1.1.0

These transaction slates are incompatible with version 1.0.1. This means users can send TO a windows wallet, but unable to receive FROM. 

https://github.com/mimblewimble/grin-wallet/issues/6#issuecomment-471373787

I will be looking into bumping the versions on all wallets to 1.1.0 

However doing this prior to the official release will put diagonAlley.io ahead of the rest of community and might drive more issues.

**Comment by BitHighlander** [comment]
I was able to force slate version in the combine binary for windows `grin-wallet` to use slate version 1. This should make all wallet versions compatible with eachother!

**Comment by xiaojay** [comment]
>I was able to force slate version in the combine binary for windows grin-wallet to use slate version 1. This should make all wallet versions compatible with eachother!

hello, how do you make this issue fixed?
and how do you build this[windows grin executable](https://github.com/BitHighlander/diagonAlley/blob/master/executables/win32/grin.exe)?

ps: I also work on a grin gui wallet :-)

Thanks
